
# LEFT SIDE
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(disk_usage ip context dir vcs)

# RIGHT SIDE
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs status history time date battery)

# ROOT ICON 
POWERLEVEL9K_HOME_ICON='🌳'

# BATTERY STAGES
# POWERLEVEL9K_BATTERY_STAGES="▁▂▃▄▅▆▇█" 
POWERLEVEL9K_BATTERY_STAGES="😡😩🙁😐🙂😌😄🤩"

# BATTERY CHARGING LEVELS
POWERLEVEL9K_BATTERY_LEVEL_BACKGROUND=(235 237 239 241 243 245 247 251)

POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE_ALWAYS="true"